### ISSUE TITLE
[Docker] api Servier not starting.

### ISSUE THREAD

**Issue by Simperfit** [Capgemini/kubeform#122]
Hi in there,

I want to try this out using docker-compose v1.7.0 and kubeform master.

I juste runned `KUBERNETES_VERSION=1.2.0 docker-compose up` and the api-server is not starting : 

apiserver     | Flag --address has been deprecated, see --insecure-bind-address instead
apiserver     | Error: unknown flag: --cluster_name
apiserver     |
apiserver     | The main API entrypoint and interface to the storage system. The API server is
apiserver     | also the focal point for all authorization decisions.

am I doing something wrong ?

**Comment by tayzlor** [comment]
Nope - our bad. https://github.com/Capgemini/kubeform/pull/123 should hopefully fix that

**Comment by tayzlor** [comment]
Feel free to re-open if you run into more trouble.

**Comment by Simperfit** [comment]
Thank you @tayzlor will test that
