### ISSUE TITLE
Terraform get error

### ISSUE THREAD

**Issue by jdumars** [Capgemini/kubeform#124]
Build machine: Ubuntu 14.04 in AWS / t2.small
Terraform v0.6.16
Python 2.7.6
ansible 2.0.2.0

Terraform fails during get:

```bash
ubuntu@terraformer:/tmp/kubeform/terraform/digitalocean$ terraform get
Get: git::https://github.com/Capgemini/tf_tls.git
Get: file:///tmp/kubeform/terraform/certs/etcd
Get: git::https://github.com/Capgemini/tf_tls.git
Error loading Terraform: Error downloading modules: module kube_apiserver_certs: open .terraform/modules/645d344e45c5efd7c2e965289931b82e/kubernetes/apiserver: no such file or directory
```

I've successfully used in other use cases with no problems.

**Comment by enxebre** [comment]
Hi thanks for reporting this, it's a bug on our do terraform code, fix is on the way.

**Comment by enxebre** [comment]
this should be fixed by https://github.com/Capgemini/kubeform/pull/126
Please feel free to reopen if you still see the issue.
Thanks!
