### ISSUE TITLE
Kubeform and kubelet - failed to detect docker ?

### ISSUE THREAD

**Issue by Simperfit** [Capgemini/kubeform#134]
Using kubeform,

I'm trying to run an container without success, looking deeply into the logs I have this line : 

`kubelet_1     | E0623 09:22:54.048622       1 container_manager_linux.go:267] failed to detect process id for "docker" - failed to find pid of "docker": exit status 1`

What can i do about that ? 

docker is up and running : 

```
systemctl status docker
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled)
   Active: active (running) since jeu. 2016-06-23 10:45:33 CEST; 42min ago
```

**Comment by enxebre** [comment]
Hey @Simperfit could you please specify which cloud are you running on?
have the deployment process finished successfully?
which command are you trying to run?
Thanks!

**Comment by Simperfit** [comment]
Hey @enxebre I'm using a debian with docker-compose up.

I was trying to create the kubernetes-dashbord or to run a nginx. None of the container are up and the pods stays on Pending.

Do you want some config information ?

Thank you for your time.
