### ISSUE TITLE
Kubernetes Dashobard login

### ISSUE THREAD

**Issue by aldarund** [Capgemini/kubeform#140]
How to login to kubernetes doashboard? 
According to blog https://capgemini.github.io/devops/kubeform/ dashboard are enabled. A
And in cluster-info it also shows

kubernetes-dashboard is running at https://../api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard

But the url seems a bit strange, official docs saying it should be accessible via /ui.
Anyway, when i try to open url from cluster-info it asks for password and login. And i dont see to find it anywhere.
It should be in kubectl config view but it shows nothing.

**Comment by enxebre** [comment]
Hey @aldarund 

after deploying the cluster if you run

```kubectl cluster-info```
you get something like
```
Kubernetes master is running at https://kube-master-61628301.eu-west-1.elb.amazonaws.com
KubeDNS is running at https://kube-master-61628301.eu-west-1.elb.amazonaws.com/api/v1/proxy/namespaces/kube-system/services/kube-dns
kubernetes-dashboard is running at https://kube-master-61628301.eu-west-1.elb.amazonaws.com/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard
Enxebre@Albertos-MacBook-Pro:~/vagrantvm/rmg-vagrant/www/apollo-kubernetes$ vim ~/.kube/config 
```
you can access to the dashboard through the elb load balancer on https by
```
 https://kube-master-61628301.eu-west-1.elb.amazonaws.com/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard
```
or
```
 https://kube-master-61628301.eu-west-1.elb.amazonaws.com/ui
```
it will ask you for the credentials so If you ssh into any of the masters you will find the default credentials here ``` /etc/kubernetes/users/known_users.csv ```
user: kube pass: changeme should just work.

Also as we are binding the insecure address to 0.0.0.0 on 8080 at the moment you could also access on http by: 
```http://master-ip:8080/ui```

In the .kube/config we handle the user and credentials for interacting to with cluster via api using Client certificate authentication.

Hope that helps!

**Comment by aldarund** [comment]
Thanks for info. I guess it would be good if u add something like this into docs :) ( And change the ansible command to a working one)
Also that blog post mentioned that
>We have additional support for Helm which can be enabled to provide the Deis Workflow by default.
But didnt saying how, neither found anything about it in docs.
I tried to edit https://github.com/Capgemini/kubeform/blob/master/roles/helm/defaults/main.yml to set helm_deis_enabled to true. But ended up with error
```
TASK [helm : install helm packages] ********************************************
failed: [kube-worker-0] (item={u'repo': u'deis/workflow', u'namespace': u'deis', u'name': u'deis'}) => {"changed": true, "cmd": ["helm", "install", "deis/workflow", "--namespace", "deis"], "delta": "0:00:00.060223", "end": "2016-07-04 22:31:31.773319", "failed": true, "item": {"name": "deis", "namespace": "deis", "repo": "deis/workflow"}, "rc": 1, "start": "2016-07-04 22:31:31.713096", "stderr": "\u001b[0;33m[WARN]\u001b[0m Oops! Looks like we had some issues running your command! Running `helm doctor` to ensure we have all the necessary prerequisites in place...\n\u001b[0;32m--->\u001b[0m Checking things locally...\n\u001b[0;32m--->\u001b[0m Creating /root/.helm/config.yaml\n\u001b[0;31m[ERROR]\u001b[0m Could not find 'kubectl' on $PATH: exec: \"kubectl\": executable file not found in $PATH", "stdout": "", "stdout_lines": [], "warnings": []}
```

**Comment by wallies** [comment]
Closing this in favour of #60, #71 and PR #143
