### ISSUE TITLE
How launch Heapster and EFK?

### ISSUE THREAD

**Issue by leandrok** [Capgemini/kubeform#179]
Hi, first of all, congratulations for your great work!

I have a KubeForm cluster deployed on DigitalOcean and I can access both the Kubernetes dashboard as well as the Traefik dashboard (on the edge router)

I have a question please. I read that Kubeform supports Heapster+InfluxDB and EFK to see the logs on Kibana. I saw some Kubernetes files related to both systems on the roles/addons/files directory.

My question is: how can I launch Heapster and the EFK stack? For example, what are the required "kubectl create -f ..." commands?

Thank you very much in advance!

Best Regards,
Leo

**Comment by enxebre** [comment]
Hey Leo!
You can enable logging and monitoring here https://github.com/Capgemini/kubeform/blob/master/group_vars/all.yml#L88
Then you can access kibana and grafana by using the proxy url you get running ```kubectl cluster-info```
You'll probably need more resources on the digitalocean machines.
Thanks!

**Comment by leandrok** [comment]
Hi Alberto!

Thank you very much for your quick reply and info!

Again, congratulations for your great work!

Cheers,
Leo
