### ISSUE TITLE
failing to run kubeform for digital ocean using terraform v0.11.3

### ISSUE THREAD

**Issue by sonamsamdupkhangsar** [Capgemini/kubeform#181]
I have been following this guide https://capgemini.github.io/kubeform/docs/getting-started-guides/digitalocean.html.  
When I run the "terraform get" command I get the following error:

Error loading configuration: Error loading /tmp/kubeform/terraform/digitalocean/main.tf: Error reading config for template_file[master_cloud_init]: parse error at 1:34: expected expression but found invalid sequence "\\"

Am I missing a step somewhere?

Thanks

**Comment by oivoodoo** [comment]
@sonamsamdupkhangsar did you resolve this issue somehow? I've just followed the same instructions and received the similar issue.

Thank you!
