### ISSUE TITLE
hyperkube/coreos versions compatibly 

### ISSUE THREAD

**Issue by enxebre** [Capgemini/kubeform#35]
The hyperkube entrypoint is /hyperkube in version 1.2

Seems to cause issues with kube-wrapper for our version of coreos

**Comment by tayzlor** [comment]
Closing this as it's /hyperkube for a reason because the CoreOS guys have deliberately moved that there and installed some relative dependencies in their container. They've since released a 1.2 container we just need to track https://quay.io/repository/coreos/hyperkube?tag=latest&tab=tags
