### ISSUE TITLE
Support ingress

### ISSUE THREAD

**Issue by tayzlor** [Capgemini/kubeform#48]
Would be good to have some out-of-the box options for Kubernetes Ingress controllers.

**Comment by enxebre** [comment]
See https://github.com/sroze/kubernetes-vamp-router

**Comment by wallies** [comment]
Needs to be more along the lines of https://github.com/nginxinc/kubernetes-ingress or even moving out to seperate machines for loadbalancing like http://www.devoperandi.com/load-balancing-in-kubernetes/

**Comment by enxebre** [comment]
could put in place a pluggable fashion approach so user can choose

**Comment by olafmol** [comment]
@enxebre VAMP is very much about high-level "canary" patterns, providing f.e. specific percentages, NOT/AND/OR logic, conditions and filter-weights, to setup complex "buckets/segments" of visitors, and route them dynamically. We currently use HAproxy's to do this, but if Ingress provides the same feature-set as HAProxy ACL's we could integrate our VampGatewayAgents with Ingres instead of HAproxy.

**Comment by wallies** [comment]
@olafmol The way I see the community going is a lot of people will use the out of the box GCE or AWS loadbalancer but this offers very simple routing. Anything more complex I see them using Ingress and Ingress controllers. The Ingress controllers are pods that listens to the /ingresses endpoint to update itself and acts as a load balancer for Ingresses. It also listens on its assigned port for external requests. People have done examples running nginx ingress controllers and i have also seen haproxy and traefik ingress controllers. So this might be the way to go

**Comment by olafmol** [comment]
@wallies Yes, it would definately be feasible to integrate/extend Ingress with VAMP and use our VampGatewayAgents(VGA's)+HAProxy as Ingress-controllers. They are already designed to run in HA & high-performance setups. This can also act as a service-loadbalancer while ingress is getting more mature. Would that make sense?

**Comment by tayzlor** [comment]
See also https://github.com/kubernetes/contrib/tree/master/ingress/controllers

**Comment by sheerun** [comment]
Traefik is pending support for it: https://github.com/containous/traefik/pull/186

**Comment by errm** [comment]
We have been using this https://github.com/albertrdixon/romulus + vulcand for a while.

**Comment by enxebre** [comment]
Closing this as https://github.com/Capgemini/kubeform/commit/ce2a684588bd80b8f9fa3fc2947136e1cab6a17b got in

Let's split the issue for the supported ingress
https://github.com/Capgemini/kubeform/issues/106
https://github.com/Capgemini/kubeform/issues/107
