### ISSUE TITLE
Investigate deis workflow integration

### ISSUE THREAD

**Issue by enxebre** [Capgemini/kubeform#68]
https://github.com/deis/workflow

**Comment by enxebre** [comment]
by the look of deis new version we should just need ```helm install deis/workflow```

**Comment by tayzlor** [comment]
Should be as simple as that yep - need to support helm first (theres a separate ticket for that)

**Comment by tayzlor** [comment]
If we add helm might want to refactor some of our "addons" to be packaged and installed via helm charts instead - we could have a separate charts repo.
